### ISSUE TITLE
messages.po with no messages

### ISSUE THREAD

**Issue by adenot** [clusteramaryllis/laravel-gettext#2]
I'm on Laravel 5.1, Windows, and I tested with both version 1.1.1 and the just added 2.0.0 with no luck.

Running php artisan gettext:create, generates all the messages.po files inside resources/locale/[lang]/LC_MESSAGES/messages.po but it only contains the header.

I have blade files under resources/views with {{ _('Welcome to application') }} and also calling _ function for some messages in controllers.

I also tried to manually put a message on messages.po but it doesn't get translated.

Am I missing anything?

**Comment by clusteramaryllis** [comment]
If you're using PoEdit you need to click the update button first then you can begin translating.

![PoEdit](http://i.imgur.com/fLaqQ5r.jpg)

See issue #1 , I already gave some example usage. thanks.

**Comment by adenot** [comment]
Oh, so that's how it works... Apologies for the silly question.

When I used gettext before, I remember that the command line tool generated a .pot file with all the messages to be translated, that served as a template for poEdit. But now poEdit does the scan for messages, that's good.

Thanks!

**Comment by adenot** [comment]
Just a follow up:
Even after I added some translations to the .po file and compiled to .mo, I still didn't get it to work after switching languages.

Then I went to php.ini and disabled php_gettext.dll (windows) and it works now!

I'm assuming that the php extension is more picky when trying to find translations, probably it's missing some parameters.

**Comment by clusteramaryllis** [comment]
not only you, i've encountered this problem also on windows! have to disable the extension.

After some searching it's a known bug on php since 5.4.19+, here's the [link](https://bugs.php.net/bug.php?id=66265).

try branch 0.3 for laravel 4.2 and use PHP < 5.4.19, it will work.
